# Generated by Django 3.1.4 on 2021-01-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=10)),
                ('capacity', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'Available'), ('F', 'Faulty'), ('R', 'On Road')], default='A', max_length=1)),
                ('type', models.CharField(choices=[('R', 'Regular'), ('E', 'Executive')], default='R', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=3)),
                ('passenger_name', models.CharField(default='', max_length=250)),
                ('passenger_phone', models.CharField(default='', max_length=10)),
                ('status', models.CharField(choices=[('B', 'Booked'), ('U', 'Not Booked')], default='U', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Bus Seats',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('A', 'Available'), ('L', 'Leave'), ('R', 'On Road')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
    ]
