# Generated by Django 3.1.4 on 2021-01-02 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_auto_20210102_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='busseat',
            name='time_booked',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
