# Generated by Django 3.1.4 on 2021-01-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0003_auto_20210102_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seat_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
